services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tips-hub-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-4000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/tips-hub-db}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - tips-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-4000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:7-jammy
    container_name: tips-hub-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=tips-hub
    volumes:
      - ./backend/mongo-data:/data/db
    networks:
      - tips-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
    driver: local

networks:
  tips-network:
    driver: bridge
