services:
  backend:
    build: ./backend
    container_name: tips-hub-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: tips-hub-frontend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: tips-hub-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    volumes:
      - ./backend/mongo-data:/data/db

volumes:
  mongo-data: